### PR TITLE
use monotonic time

### PR DESCRIPTION
**Pull request by mikz**
see https://github.com/ruby-concurrency/concurrent-ruby/issues/256 for more information

Main reason is that your test **can** stub `Time`. So measuring duration of tests by that can get affected.
Similar thing was resolved in cucumber 2. See https://github.com/cucumber/cucumber-ruby-core/issues/101

### CODE REVIEW

**Comment by shepmaster** [comment]
Thanks! I don't suppose there is a gem that would provide this logic already, is there? It seems pretty out-of-scope for CI::Reporter to know about the underlying Ruby interpreter!

Out of curiosity, did you experience any concrete problems from the use of a time source that could be monkeyed with?

**Comment by shepmaster** [comment]
> a gem that would provide this logic

Especially if the same thing has already been copied into two other projects...

**Comment by mikz** [comment]
@shepmaster there is `concurrent-ruby` implementation, but that looks like an overkill.  I have not seen any other reasonable cross platform implementation.

Yes, my test suite runs -30 days and other random numbers.

**Comment by mikz** [comment]
Just btw, I as a developer would pick copied code like this in my dependencies over having possibility of a version clash when trying to upgrade. Or installing another gem.

**Comment by mikz** [comment]
@shepmaster this is rebased and green. I really don't think it is worth to abstract this somewhere.
You generally needs this in concurrent environments for timeouts or when measuring duration of tests (which can stub time).

**Comment by shepmaster** [comment]
> I really don't think it is worth to abstract this somewhere.

I understand your feelings, but I don't agree with them 😸 As you can tell by my long response times, this is a low-touch project, and I'm not excited to maintain ~30 lines of code that from all appearances appear to be highly specific to a given Ruby interpreter. 

I do agree that this kind of thing would be highly valuable. I could see accepting a PR that refactors CI::Reporter to allow injecting some kind of `TimeSource`. That would allow you to maintain those 30 lines of code in each of your projects, while not having to maintain a hacked-up version of CI::Reporter. How's that sound?

**Comment by mikz** [comment]
>  How's that sound?

Better than having a gem dependency. 

But still I don't think it is acceptable default experience. Have you considered adding more maintainers to the project, so it is not just yours responsibility?

**Comment by Bertg** [comment]
```Process.clock_gettime(Process::CLOCK_MONOTONIC)``` is supported by jRuby >9.0.0. So we could remove the check for jRuby. Older jRuby version would still use the ```Time.now``` fallback.

As a compromise between the argument ``` It seems pretty out-of-scope for CI::Reporter to know about the underlying Ruby interpreter``` and the desire to add monotonic time. 

Would that be acceptable?

**Comment by mikz** [comment]
@Bertg great! Will update the patch. Looks like there is no `Process::CLOCK_MONOTONIC` in JRuby 1.7.

**Comment by mikz** [comment]
@shepmaster is it small enough now? It is really just getting time.

**Comment by Bertg** [comment]
Looks great to me 👍

**Comment by Bertg** [comment]
@shepmaster I was actually planning to make this PR as well. I got inspired by this post: https://blog.dnsimple.com/2018/03/elapsed-time-with-ruby-the-right-way/

**Comment by nicksieger** [comment]
Looks ok to me, let's try this.

**Comment by Bertg** [comment]
I have never seen a PR this old get merged in. Without any sense of sarcasm: this is amazing. 
Thanks @nicksieger for picking this up.

**Pull request merged**
